# Generated by Django 3.0.11 on 2023-01-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=255, verbose_name='Match')),
                ('game', models.IntegerField(verbose_name='Game')),
                ('team', models.CharField(max_length=150, verbose_name='Team')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('v_2p', models.FloatField(verbose_name='2P')),
            ],
        ),
    ]
