# Generated by Django 4.1.5 on 2023-02-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match', models.CharField(max_length=255, null=True, verbose_name='match')),
                ('Game', models.CharField(max_length=10, null=True, verbose_name='game')),
                ('Team', models.CharField(max_length=150, null=True, verbose_name='team')),
                ('Name', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('v_2p', models.FloatField(verbose_name='value1')),
            ],
        ),
    ]
