# Generated by Django 3.0.11 on 2023-03-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='park_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=10)),
                ('game', models.CharField(max_length=10)),
                ('team', models.CharField(max_length=20)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=255, null=True, verbose_name='match')),
                ('year', models.CharField(max_length=50, null=True, verbose_name='year')),
                ('game', models.CharField(max_length=10, null=True, verbose_name='game')),
                ('date', models.CharField(max_length=50, null=True, verbose_name='date')),
                ('team', models.CharField(max_length=150, null=True, verbose_name='team')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='name')),
                ('score_total', models.CharField(default='', max_length=10, null=True, verbose_name='score_total')),
                ('game_time', models.CharField(max_length=50, null=True, verbose_name='game_time')),
                ('kpi_2p', models.FloatField(null=True, verbose_name='kpi_2p')),
                ('kpi_2pA', models.FloatField(null=True, verbose_name='kpi_2pA')),
                ('kpi_2pp', models.FloatField(null=True, verbose_name='kpi_2pp')),
                ('kpi_3p', models.FloatField(null=True, verbose_name='kpi_3p')),
                ('kpi_3pA', models.FloatField(null=True, verbose_name='kpi_3pA')),
                ('kpi_3pp', models.FloatField(null=True, verbose_name='kpi_3pp')),
                ('kpi_FGp', models.FloatField(null=True, verbose_name='kpi_FGp')),
                ('kpi_FT', models.FloatField(null=True, verbose_name='kpi_FT')),
                ('kpi_FTA', models.FloatField(null=True, verbose_name='kpi_FTA')),
                ('kpi_FTp', models.FloatField(null=True, verbose_name='kpi_FTp')),
                ('kpi_REB_OR', models.FloatField(null=True, verbose_name='kpi_REB_OR')),
                ('kpi_REB_DF', models.FloatField(null=True, verbose_name='kpi_REB_DF')),
                ('kpi_REB_TOT', models.FloatField(null=True, verbose_name='kpi_REB_TOT')),
                ('kpi_AS', models.FloatField(null=True, verbose_name='kpi_AS')),
                ('kpi_ST', models.FloatField(null=True, verbose_name='kpi_ST')),
                ('kpi_GD', models.FloatField(null=True, verbose_name='kpi_GD')),
                ('kpi_BS', models.FloatField(null=True, verbose_name='kpi_BS')),
                ('kpi_PF_w', models.FloatField(null=True, verbose_name='kpi_PF_W')),
                ('kpi_PF_wo', models.FloatField(null=True, verbose_name='kpi_PF_wo')),
                ('kpi_PF_TOT', models.FloatField(null=True, verbose_name='kpi_PF_TOT')),
                ('kpi_TO', models.FloatField(null=True, verbose_name='kpi_TO')),
                ('kpi_TF', models.FloatField(null=True, verbose_name='kpi_TF')),
            ],
        ),
    ]
