# Generated by Django 3.0.11 on 2023-01-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='game',
        ),
        migrations.RemoveField(
            model_name='test',
            name='match',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='team',
        ),
        migrations.AddField(
            model_name='test',
            name='Game',
            field=models.IntegerField(null=True, verbose_name='game'),
        ),
        migrations.AddField(
            model_name='test',
            name='Match',
            field=models.CharField(max_length=255, null=True, verbose_name='match'),
        ),
        migrations.AddField(
            model_name='test',
            name='Name',
            field=models.CharField(max_length=150, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='test',
            name='Team',
            field=models.CharField(max_length=150, null=True, verbose_name='team'),
        ),
        migrations.AlterField(
            model_name='test',
            name='v_2p',
            field=models.FloatField(null=True, verbose_name='v_2p'),
        ),
    ]
