# Generated by Django 3.0.11 on 2023-01-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_auto_20230118_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Game',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='Match',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='Name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='Team',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='v_2p',
            field=models.IntegerField(null=True),
        ),
    ]
