# Generated by Django 3.0.11 on 2023-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_auto_20230118_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='v_2p',
            field=models.IntegerField(default='', null=True),
        ),
    ]
