# Generated by Django 3.0.11 on 2023-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0004_auto_20230118_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Game',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='v_2p',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
