# Generated by Django 4.1.5 on 2023-03-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_file',
            field=models.FileField(upload_to='upload_file/%Y/m%d/'),
        ),
    ]
